version: "3"
services:
  proxy:
    build: ./proxy
    privileged: true # for chrome
    ports:
      - "4000:80"
    links:
      - backend
      - renderer
    networks:
      - backend
    restart: always
  renderer:
    build: ./renderer
    privileged: true # for chrome
    links:
      - backend
    networks:
      - backend
  backend:
    build: ./example
    networks:
      - backend
networks:
  backend: {}
